name: YPluginEncryptor
api: 
- 3.0.0
- 4.0.0
version: 1.1.0_api400
load: POSTWORLD
main: YMind\xMing\YPluginEncryptor\Main
author: xMing 
commands:
  ympe:
    description: "加密插件操作"
    permission: ympe.command
permissions:
  ympe.command: 
    default: op
